// <auto-generated />
using DbOutOfNames.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DbOutOfNames.Migrations
{
    [DbContext(typeof(PersonContext))]
    [Migration("20211116030659_Country")]
    partial class Country
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DbOutOfNames.Models.Country", b =>
                {
                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countrys");

                    b.HasData(
                        new
                        {
                            CountryId = "C",
                            Name = "Canada"
                        },
                        new
                        {
                            CountryId = "D",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            CountryId = "E",
                            Name = "Ecaudor"
                        },
                        new
                        {
                            CountryId = "M",
                            Name = "Mexico"
                        },
                        new
                        {
                            CountryId = "U",
                            Name = "United States"
                        });
                });

            modelBuilder.Entity("DbOutOfNames.Models.Person", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("First")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.HasKey("Email");

                    b.HasIndex("CountryId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Email = "CoffeeNotCode@yahoo.com",
                            CountryId = "C",
                            First = "Sam",
                            Last = "Relational",
                            Password = "R0CKYOu99999999"
                        },
                        new
                        {
                            Email = "3MonsterEnergy@MoreRedbull.com",
                            CountryId = "D",
                            First = "Jackie",
                            Last = "Nonrelational",
                            Password = "PlainText4ThatWin"
                        },
                        new
                        {
                            Email = "Java>SQL@truestatement.net",
                            CountryId = "E",
                            First = "Selma",
                            Last = "Crowsfoot",
                            Password = "S3lmaCrowsf00t"
                        },
                        new
                        {
                            Email = "NoMoDb@ThatNastyDB.com",
                            CountryId = "M",
                            First = "Senor",
                            Last = "Casablanca",
                            Password = ""
                        },
                        new
                        {
                            Email = "ItsBrokenAgain@Shocker.com",
                            CountryId = "U",
                            First = "Trevor",
                            Last = "Lastelick",
                            Password = "C4ntH4ckM3"
                        });
                });

            modelBuilder.Entity("DbOutOfNames.Models.Person", b =>
                {
                    b.HasOne("DbOutOfNames.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
